"""i18n FR/EN de l'interface Terroir Context Agents.

`MSG[key] = {"fr": ..., "en": ...}` centralise tous les libellés visibles.
Les modules de rendu acceptent un paramètre `lang="fr"` ; l'application
(pilote par session Streamlit) utilise `T(key, **fmt)`.

Ce qui reste dans la langue de la donnée (et le restera) : les intitulés de
sources publiques (Hub'Eau, RPG, SoilGrids), les tokens d'état
(`sûr`/`vigilance`/`rupture`, valeurs de données et tests) et les phrases
générées par les services (certificat de données, audit expert).
"""

from __future__ import annotations

MS = "fr"
M = "en"

MSG: dict[str, dict[str, str]] = {
    # --- Navigation --------------------------------------------------------
    "nav.vision": {MS: "Vision", M: "Vision"},
    "nav.application": {MS: "Application", M: "Application"},
    "nav.graph": {MS: "Graphe & IA", M: "Graph & AI"},
    "nav.contact": {MS: "Contact", M: "Contact"},

    # --- Landing : hero ------------------------------------------------------
    "hero.eyebrow": {MS: "DÉCISION AGRICOLE SOURCÉE — DATAHUB, MCP & IA", M: "SOURCED FARMING DECISION — DATAHUB, MCP & AI"},
    "hero.title": {MS: "Choisir sa culture avec des <em>preuves</em>, pas des intuitions", M: "Choose your crop with <em>evidence</em>, not intuition"},
    "hero.lead": {
        MS: "Terroir Context Agents compare les cultures d'une parcelle réelle à partir de données ouvertes tracées : sol, eau, climat, marchés. Chaque chiffre est relié à sa source, contrôlé par un agent de supervision, et barré s'il devient périmé.",
        M: "Terroir Context Agents compares crops on a real parcel using traced open data: soil, water, climate, markets. Every figure is linked to its source, checked by a supervision agent, and struck out when it becomes stale.",
    },
    "hero.cta.analyze": {MS: "Analyser ma parcelle", M: "Analyze my parcel"},
    "hero.cta.graph": {MS: "Voir le graphe & l'IA", M: "See the graph & AI"},
    "hero.chip.sources": {MS: "11 sources de données", M: "11 data sources"},
    "hero.chip.crops": {MS: "3 cultures comparées", M: "3 crops compared"},
    "hero.chip.mcp": {MS: "12 outils MCP", M: "12 MCP tools"},

    # --- Landing : stats ------------------------------------------------------
    "stats.sources": {MS: "sources de données tracées", M: "traced data sources"},
    "stats.crops": {MS: "cultures comparées par parcelle", M: "crops compared per parcel"},
    "stats.steps": {MS: "étapes du parcours décisionnel", M: "steps of the decision journey"},
    "stats.mcp": {MS: "outils MCP pour un agent", M: "MCP tools for an agent"},

    # --- Landing : à propos ----------------------------------------------------
    "about.eyebrow": {MS: "NOTRE MISSION", M: "OUR MISSION"},
    "about.title": {MS: "Un conseil fondé sur les données, pas sur l'intuition", M: "Advice grounded in data, not intuition"},
    "about.p1": {
        MS: "Comme un cabinet accompagne un dirigeant, Terroir Context Agents accompagne l'agriculteur dans son choix de culture : chaque recommandation s'appuie sur des données publiques vérifiées (RPG, Hub'Eau, SoilGrids, prévisions saisonnières) assemblées dans un graphe de contexte DataHub.",
        M: "Like a firm advising an executive, Terroir Context Agents supports the farmer's crop choice: every recommendation relies on verified public data (RPG, Hub'Eau, SoilGrids, seasonal forecasts) assembled in a DataHub context graph.",
    },
    "about.p2": {
        MS: "Un agent MCP supervise en continu la fraîcheur des sources : si une station ne répond plus, les recommandations devenues fragiles sont barrées et un incident est ouvert dans le graphe. La décision reste humaine — les preuves, elles, sont auditées.",
        M: "An MCP agent continuously supervises source freshness: if a station stops responding, fragile recommendations are struck out and an incident is opened in the graph. The decision stays human — the evidence is audited.",
    },
    "about.check1": {MS: "Traçabilité complète de la source jusqu'au chiffre", M: "Full traceability from source to figure"},
    "about.check2": {MS: "Fraîcheur contrôlée par SLA, périmés signalés", M: "SLA-controlled freshness, staleness flagged"},
    "about.check3": {MS: "Chiffres déterministes, aucun généré par un LLM", M: "Deterministic figures, none generated by an LLM"},
    "about.caption": {MS: "parcelle RPG réelle · géométrie WGS84 · sol SoilGrids", M: "real RPG parcel · WGS84 geometry · SoilGrids soil"},

    # --- Landing : valeurs ------------------------------------------------------
    "values.eyebrow": {MS: "NOS VALEURS", M: "OUR VALUES"},
    "values.title": {MS: "Trois engagements pour chaque décision", M: "Three commitments behind every decision"},
    "values.transparence": {MS: "Transparence", M: "Transparency"},
    "values.transparence.text": {MS: "Chaque chiffre est relié à sa source, sa licence et son niveau de preuve dans le graphe.", M: "Every figure is linked to its source, license and evidence level in the graph."},
    "values.autonomie": {MS: "Autonomie", M: "Autonomy"},
    "values.autonomie.text": {MS: "L'agent de supervision contrôle la fraîcheur et l'impact du lineage sans intervention humaine.", M: "The supervision agent checks freshness and lineage impact with no human intervention."},
    "values.fiabilite": {MS: "Fiabilité", M: "Reliability"},
    "values.fiabilite.text": {MS: "Les formules sont déterministes et documentées ; le certificat de données dit ce qui est prouvé.", M: "Formulas are deterministic and documented; the data certificate states what is proven."},

    # --- Landing : expertises -----------------------------------------------------
    "expertise.eyebrow": {MS: "NOS DOMAINES D'EXPERTISE", M: "OUR AREAS OF EXPERTISE"},
    "expertise.title": {MS: "Trois piliers de données, un seul graphe", M: "Three data pillars, one graph"},
    "expertise.card1.title": {MS: "Parcelle & sol", M: "Parcel & soil"},
    "expertise.card1.text": {MS: "Le RPG public, la géométrie réelle des parcelles et le sol (SoilGrids ou analyse déclarée).", M: "The public RPG, real parcel geometry and soil (SoilGrids or user-declared analysis)."},
    "expertise.card2.title": {MS: "Eau & climat", M: "Water & climate"},
    "expertise.card2.text": {MS: "Les stations Hub'Eau en service, la réserve utile, la fenêtre de tension et les prévisions.", M: "Active Hub'Eau stations, useful water reserve, the stress window and forecasts."},
    "expertise.card3.title": {MS: "Économie & marchés", M: "Economics & markets"},
    "expertise.card3.text": {MS: "Prix, charges et aides à remplacer par les valeurs de l'exploitation, marge recalculée.", M: "Prices, costs and subsidies to replace with farm values, recomputed margin."},
    "expertise.explore": {MS: "Explorer", M: "Explore"},

    # --- Landing : approche --------------------------------------------------------
    "approach.eyebrow": {MS: "NOTRE APPROCHE", M: "OUR APPROACH"},
    "approach.title": {MS: "Une méthode différenciante, techniquement documentée", M: "A differentiating, technically documented method"},
    "approach.step1.title": {MS: "Une expertise pointue", M: "Sharp expertise"},
    "approach.step1.text": {MS: "Maîtrise des rouages de la donnée agricole : chaque source est qualifiée par son niveau de preuve (mesure, modélisation, dire d'expert).", M: "Mastery of agricultural data mechanics: every source is qualified by its evidence level (measurement, modeling, expert statement)."},
    "approach.step2.title": {MS: "Une approche orientée résultats", M: "A results-driven approach"},
    "approach.step2.text": {MS: "Les recommandations sont directement applicables : calendrier, eau, marge — avec un impact mesurable sur la décision de semis.", M: "Recommendations are directly actionable: calendar, water, margin — with measurable impact on the sowing decision."},
    "approach.step3.title": {MS: "Un accompagnement immersif", M: "Immersive support"},
    "approach.step3.text": {MS: "L'agent de supervision travaille dans votre graphe DataHub : fraîcheur, lineage, incidents et runs y sont tracés en continu.", M: "The supervision agent works inside your DataHub graph: freshness, lineage, incidents and runs are continuously traced."},

    # --- Hero application ------------------------------------------------------------
    "apphero.eyebrow": {MS: "L'APPLICATION — LE TUNNEL DE DÉCISION", M: "THE APP — THE DECISION TUNNEL"},
    "apphero.lead": {
        MS: "Saisissez votre commune, chargez les parcelles réelles du RPG et recevez une comparaison sourcée des trois cultures : calendrier, eau, marge, confiance. Chaque chiffre est tracé jusqu'à sa source dans le graphe DataHub.",
        M: "Enter your municipality, load the real RPG parcels and get a sourced comparison of the three crops: calendar, water, margin, confidence. Every figure is traced to its source in the DataHub graph.",
    },
    "apphero.chip.parcels": {MS: "parcelles RPG réelles", M: "real RPG parcels"},
    "apphero.chip.crops": {MS: "3 cultures comparées", M: "3 crops compared"},
    "apphero.chip.certificate": {MS: "certificat de données", M: "data certificate"},
    "apphero.card": {MS: "Parcelle RPG réelle, commune saisie, sources de secours essayées dans l'ordre.", M: "Real RPG parcel, entered municipality, fallback sources tried in order."},

    # --- CTA / footer ----------------------------------------------------------------
    "cta.title": {MS: "Prêt à comparer vos cultures sur votre parcelle ?", M: "Ready to compare your crops on your parcel?"},
    "cta.text": {
        MS: "Entrez votre commune, chargez les parcelles réelles du RPG et recevez une comparaison sourcée, avec le certificat de données et les KPIs de confiance.",
        M: "Enter your municipality, load the real RPG parcels and get a sourced comparison, with the data certificate and confidence KPIs.",
    },
    "cta.btn": {MS: "Analyser ma parcelle →", M: "Analyze my parcel →"},
    "footer.tagline": {MS: "Partenaire de la décision agricole : données ouvertes, graphe DataHub et agent MCP de supervision. Projet du hackathon Build with DataHub.", M: "Partner of the farming decision: open data, DataHub graph and MCP supervision agent. Build with DataHub hackathon project."},
    "footer.contact_title": {MS: "Contact", M: "Contact"},
    "footer.online": {MS: "Application en ligne", M: "Live application"},
    "footer.links_title": {MS: "Liens utiles", M: "Useful links"},
    "footer.legal": {MS: "© 2026 Terroir Context Agents — Apache 2.0 · données : Licence Ouverte / Etalab 2.0 · format inspiré de consilium-bsf.fr/vision", M: "© 2026 Terroir Context Agents — Apache 2.0 · data: Licence Ouverte / Etalab 2.0 · layout inspired by consilium-bsf.fr/vision"},

    # --- Tunnel ----------------------------------------------------------------
    "tunnel.title": {MS: "Choisir sa culture", M: "Choose your crop"},
    "tunnel.step": {MS: "Étape {current} / {total}", M: "Step {current} / {total}"},
    "tunnel.question_kicker": {MS: "VOTRE PARCELLE", M: "YOUR PARCEL"},
    "tunnel.question_line1": {MS: "Ce que vous vous apprêtez à semer", M: "What you are about to sow"},
    "tunnel.question_line2": {MS: "aura-t-il soif au moment où", M: "will it get thirsty at the moment"},
    "tunnel.question_line3": {MS: "il n'y aura plus d'eau ?", M: "when there is no more water?"},
    "tunnel.intro1.title": {MS: "Ce que fait cet outil", M: "What this tool does"},
    "tunnel.intro1.text": {MS: "Compare le calendrier de vos cultures à la tension en eau prévue sur la parcelle, pour repérer une soif au mauvais moment avant de semer.", M: "Compares your crops' calendar against the expected water stress on the parcel, to spot a thirst at the wrong time before sowing."},
    "tunnel.intro2.title": {MS: "Ce qu'il ne fait pas", M: "What it does not do"},
    "tunnel.intro2.text": {MS: "Ne remplace pas une expertise agronomique, ne garantit pas un rendement, ne déclenche aucune irrigation.", M: "Does not replace agronomic expertise, does not guarantee a yield, does not trigger any irrigation."},

    # --- Écran question -------------------------------------------------------------
    "q.commune": {MS: "Commune", M: "Municipality"},
    "q.commune.help": {MS: "Saisissez la commune où se trouve votre parcelle.", M: "Enter the municipality where your parcel is located."},
    "q.search": {MS: "Chercher les parcelles", M: "Search parcels"},
    "q.found": {MS: "{n} parcelle(s) trouvée(s).", M: "{n} parcel(s) found."},
    "q.error": {MS: "Impossible de charger les données publiques. {exc}", M: "Could not load public data. {exc}"},
    "q.info": {MS: "Saisissez une commune puis cliquez sur « Chercher les parcelles » pour charger les parcelles réelles du RPG.", M: "Enter a municipality then click “Search parcels” to load the real RPG parcels."},
    "q.caption_rpg": {MS: "RPG {year} · INSEE {code}", M: "RPG {year} · INSEE {code}"},
    "q.parcel": {MS: "Parcelle", M: "Parcel"},
    "q.sowing": {MS: "Date de semis envisagée", M: "Planned sowing date"},
    "q.horizon": {MS: "Durée étudiée", M: "Time horizon"},
    "q.horizon.fmt": {MS: "{value} mois", M: "{value} months"},
    "q.horizon.caption": {MS: "3 mois : le plus fiable · 6 mois : plus incertain · 12 mois : tendance climatique", M: "3 months: most reliable · 6 months: more uncertain · 12 months: climate trend"},
    "q.soil.spinner": {MS: "Recherche des informations de sol…", M: "Looking up soil information…"},
    "q.soil.kicker": {MS: "Analyse de sol de la parcelle", M: "Parcel soil analysis"},
    "q.soil.type": {MS: "Sol", M: "Soil"},
    "q.soil.ru": {MS: "Réserve utile", M: "Useful reserve"},
    "q.soil.details": {MS: "Détails et confiance de l'analyse de sol", M: "Soil analysis details & confidence"},
    "q.soil.confidence": {MS: "Confiance", M: "Confidence"},
    "q.soil.known_type": {MS: "Type de sol mesuré", M: "Measured soil type"},
    "q.soil.known_ru": {MS: "Réserve utile mesurée (mm)", M: "Measured useful reserve (mm)"},
    "q.soil.use_mine": {MS: "Utiliser mon analyse", M: "Use my analysis"},
    "q.map": {MS: "Voir la parcelle et les stations d’eau sur la carte", M: "See the parcel and water stations on the map"},
    "q.analyze": {MS: "Analyser ma parcelle", M: "Analyze my parcel"},

    # --- Écran résultat ------------------------------------------------------------
    "res.kicker": {MS: "LE RÉSULTAT", M: "THE RESULT"},
    "res.verdict_kicker": {MS: "Ce qu'il faut retenir", M: "What to remember"},
    "res.no_crops": {MS: "Aucune culture ne peut être chiffrée avec ce niveau de confiance.", M: "No crop can be estimated at this confidence level."},
    "res.confidence.high": {MS: "Confiance haute — toutes les données sont à jour et traçables.", M: "High confidence — all data is up to date and traceable."},
    "res.confidence.degraded.title": {MS: "À confirmer avec vos chiffres.", M: "To be confirmed with your own figures."},
    "res.confidence.degraded.text": {MS: "Nous utilisons des prix et des charges moyens. Remplacez-les par vos données avant de décider.", M: "We use average prices and costs. Replace them with your data before deciding."},
    "res.confidence.impossible": {MS: "Calcul impossible.", M: "Calculation impossible."},
    "res.tab.why": {MS: "Pourquoi ce classement", M: "Why this ranking"},
    "res.tab.compare": {MS: "Comparer deux cultures", M: "Compare two crops"},
    "res.tab.calendar": {MS: "Calendrier & eau", M: "Calendar & water"},
    "res.tab.simulate": {MS: "Simuler mes prix", M: "Simulate my prices"},
    "res.tab.report": {MS: "Rapport", M: "Report"},
    "res.crop_a": {MS: "Culture actuelle", M: "Current crop"},
    "res.crop_b": {MS: "Culture envisagée", M: "Planned crop"},
    "res.compare.caption": {MS: "Comparez librement deux cultures de la comparaison : eau, coût, marge et risque.", M: "Compare any two crops: water, cost, margin and risk."},
    "res.calendar.caption": {MS: "Besoins d'irrigation répartis sur le cycle de chaque culture, avec la fenêtre de tension hydrique.", M: "Irrigation needs spread over each crop's cycle, with the water stress window."},
    "res.levers": {MS: "Comment sécuriser {crop}", M: "How to secure {crop}"},
    "res.sim.heading": {MS: "Simulez avec vos propres chiffres", M: "Simulate with your own figures"},
    "res.sim.caption": {MS: "Remplacez ces valeurs par les vôtres pour les trois cultures d'un coup. Le calendrier et le classement restent ceux du scénario ; seule la marge simulée change.", M: "Replace these values with yours for all three crops at once. The calendar and ranking stay those of the scenario; only the simulated margin changes."},
    "res.sim.col.culture": {MS: "Culture", M: "Crop"},
    "res.sim.col.rendement": {MS: "Rendement (q/ha)", M: "Yield (q/ha)"},
    "res.sim.col.prix": {MS: "Prix (€/q)", M: "Price (€/q)"},
    "res.sim.col.aides": {MS: "Aides (€/ha)", M: "Subsidies (€/ha)"},
    "res.sim.col.semences": {MS: "Semences (€/ha)", M: "Seeds (€/ha)"},
    "res.sim.col.ferti": {MS: "Fertilisation (€/ha)", M: "Fertilization (€/ha)"},
    "res.sim.col.protection": {MS: "Protection (€/ha)", M: "Protection (€/ha)"},
    "res.sim.col.travaux": {MS: "Travaux/carburant (€/ha)", M: "Work/fuel (€/ha)"},
    "res.sim.col.sechage": {MS: "Séchage (€/ha)", M: "Drying (€/ha)"},
    "res.sim.col.prestation": {MS: "Prestation (€/ha)", M: "Services (€/ha)"},
    "res.sim.col.eau": {MS: "Eau (€/m³)", M: "Water (€/m³)"},
    "res.report.subhead": {MS: "Rapport de comparaison", M: "Comparison report"},
    "res.report.btn": {MS: "Générer et archiver le rapport", M: "Generate & archive the report"},
    "res.report.done": {MS: "Rapport archivé — le CSV est prêt à droite.", M: "Report archived — the CSV is ready on the right."},
    "res.report.dl": {MS: "Télécharger le rapport (CSV)", M: "Download the report (CSV)"},
    "res.proof": {MS: "Voir le certificat de données et le détail technique", M: "See the data certificate and technical details"},
    "res.proof.tracability": {MS: "Traçabilité vérifiée", M: "Verified traceability"},
    "res.proof.strong": {MS: "preuves fortes", M: "strong pieces of evidence"},
    "res.proof.cert": {MS: "CERTIFICAT DES DONNÉES", M: "DATA CERTIFICATE"},
    "res.proof.subhead": {MS: "Le graphe de lineage — chaque chiffre a un chemin", M: "The lineage graph — every figure has a path"},
    "res.proof.all": {MS: "Voir tous les chiffres et la confiance", M: "See all figures and confidence"},
    "res.proof.attempts": {MS: "Sources de secours essayées", M: "Fallback sources tried"},
    "res.proof.expert": {MS: "Vue experte : audit des données et des modèles", M: "Expert view: data & model audit"},
    "res.proof.expert.score": {MS: "SCORE TECHNIQUE MOYEN", M: "AVERAGE TECHNICAL SCORE"},
    "res.proof.expert.score.note": {MS: "Ce score résume la qualité technique des entrées. Il ne prédit pas le rendement futur.", M: "This score summarizes the technical quality of inputs. It does not predict future yield."},
    "res.proof.expert.collected": {MS: "Données collectées", M: "Collected data"},
    "res.proof.expert.failed": {MS: "Sources en échec", M: "Failed sources"},
    "res.proof.expert.models": {MS: "Modèles utilisés", M: "Models used"},
    "res.proof.expert.scores": {MS: "Scores", M: "Scores"},
    "res.proof.expert.nofailed": {MS: "Aucun échec de source enregistré sur cette exécution.", M: "No source failure recorded on this run."},
    "res.proof.expert.params": {MS: "Paramètres du scénario", M: "Scenario parameters"},
    "res.proof.expert.bar": {MS: "Barème : élevée = 100, moyenne = 65, faible = 30, insuffisante = 0.", M: "Scale: high = 100, medium = 65, low = 30, insufficient = 0."},
    "res.summary.crops": {MS: "{n} culture(s) comparée(s) pour {id}", M: "{n} crop(s) compared for {id}"},
    "res.summary.best": {MS: " — {crop} recommandée (marge {margin} €/ha, état {state})", M: " — {crop} recommended (margin {margin} €/ha, state {state})"},

    # --- Timeline / analyse / leviers / classement ------------------------------------
    "tl.margin_ha": {MS: "Marge/ha", M: "Margin/ha"},
    "tl.legend.how": {MS: "Comment lire :", M: "How to read:"},
    "tl.legend.neutral": {MS: "Tension neutre", M: "Neutral stress"},
    "tl.legend.amber": {MS: "Ambre — sécheresse probable", M: "Amber — likely drought"},
    "tl.legend.red": {MS: "Rouge — restriction probable", M: "Red — likely restriction"},
    "tl.legend.critical": {MS: "Stade critique", M: "Critical stage"},
    "tl.legend.critical_tension": {MS: "Stade critique sous tension forte", M: "Critical stage under strong stress"},
    "tl.tension": {MS: "Tension eau", M: "Water stress"},
    "tl.collision": {MS: "Collision — soif en pleine tension", M: "Collision — thirst right in the stress window"},
    "tl.water_title": {MS: "Lame d'eau mensuelle (mm/mois)", M: "Monthly water need (mm/month)"},
    "tl.water_stress": {MS: "FENÊTRE DE TENSION HYDRIQUE", M: "WATER STRESS WINDOW"},
    "tl.water_aria": {MS: "Lame d'eau mensuelle par culture", M: "Monthly water need per crop"},
    "tl.calendar_caption": {MS: "Tendance climatologique, pas une prévision individuelle.", M: "Climatological trend, not an individual forecast."},

    "an.analysis": {MS: "Analyse — {commune} — {date}", M: "Analysis — {commune} — {date}"},
    "an.no_risk.title": {MS: "Aucune collision entre les cultures et la tension en eau", M: "No collision between the crops and the water stress"},
    "an.no_risk.body": {MS: "Sur {commune}, les {n} cultures comparées traversent leur stade critique en dehors de la période de tension prévue sur l'eau. Aucun ajustement du calendrier n'est nécessaire dans ce scénario.", M: "On {commune}, the {n} compared crops cross their critical stage outside the expected water stress period. No calendar adjustment is needed in this scenario."},
    "an.worst.title": {MS: "Le {crop} rejoue le même pari sur l'eau", M: "{crop} plays the same bet on water again"},
    "an.worst.p1": {MS: "Sur {commune}, {stage} du {crop} semé au {sow} tombe du {start} au {end} — {relation} dans la fenêtre où le modèle prévoit la tension en eau la plus forte.", M: "On {commune}, the {stage} of {crop} sown on {sow} falls from {start} to {end} — {relation} in the window where the model forecasts the strongest water stress."},
    "an.exactly": {MS: "exactement", M: "exactly"},
    "an.partially": {MS: "en partie", M: "partly"},
    "an.safe": {MS: "{names} traverse son stade critique en dehors de la tension, avec une marge supérieure de {margin} €/ha à celle du {crop}.", M: "{names} crosses its critical stage outside the stress, with a margin {margin} €/ha higher than {crop}."},
    "an.safe.plural": {MS: "{names} traversent leur stade critique en dehors de la tension, avec une marge supérieure de {margin} €/ha à celle du {crop}.", M: "{names} cross their critical stage outside the stress, with a margin {margin} €/ha higher than {crop}."},
    "an.leviers": {MS: " Si le {crop} est maintenu, les leviers ci-dessous permettent de réduire son exposition.", M: " If {crop} is kept, the levers below reduce its exposure."},
    "an.to": {MS: "{a} à {b}", M: "{a} to {b}"},

    "lv.no_risk": {MS: "Aucune culture à risque : rien à corriger.", M: "No crop at risk: nothing to correct."},
    "lv.title": {MS: "Comment éviter — {crop}", M: "How to avoid — {crop}"},
    "lv.none": {MS: "Aucun levier calculable pour cette culture sur cette parcelle. Le plus sûr reste de comparer avec une culture dont le stade critique tombe hors tension.", M: "No lever can be computed for this crop on this parcel. The safest option remains comparing with a crop whose critical stage falls outside the stress."},
    "lv.days": {MS: "{days} j → {after} j", M: "{days} d → {after} d"},

    "rc.scenario": {MS: "Marge scénario", M: "Scenario margin"},
    "rc.simulated": {MS: "Marge simulée", M: "Simulated margin"},
    "rc.identical": {MS: "identique au scénario", M: "identical to scenario"},
    "rc.vs": {MS: "{delta} €/ha vs scénario", M: "{delta} €/ha vs scenario"},

    "verdict.empty": {MS: "Aucune culture ne peut être comparée avec ce niveau de confiance.", M: "No crop can be compared at this confidence level."},
    "verdict.single": {MS: "Sur cette parcelle, {crop} est l'option la plus sûre parmi celles comparées — {risk}.", M: "On this parcel, {crop} is the safest option among those compared — {risk}."},
    "verdict.multi": {MS: "Sur cette parcelle, {crop} est l'option la plus sûre : +{diff} €/ha vs {worst}, {risk}.", M: "On this parcel, {crop} is the safest option: +{diff} €/ha vs {worst}, {risk}."},
    "verdict.no_risk": {MS: "aucun risque hydrique", M: "no water risk"},
    "verdict.days": {MS: "{days} jours à surveiller", M: "{days} days to watch"},

    "rk.culture": {MS: "Culture", M: "Crop"},
    "rk.state": {MS: "État", M: "State"},
    "rk.margin": {MS: "Marge", M: "Margin"},
    "rk.water": {MS: "Eau", M: "Water"},
    "rk.main_risk": {MS: "Risque principal", M: "Main risk"},
    "rk.none": {MS: "Aucun", M: "None"},
    "rk.risk": {MS: "{stage} — {days} j sous tension", M: "{stage} — {days} d under stress"},

    "reason.safe": {MS: "{crop} : {stage} tombe hors tension — aucun risque.", M: "{crop}: {stage} falls outside the stress — no risk."},
    "reason.full": {MS: "{crop} : {stage} du {start} au {end} tombe en pleine tension — {days} j de recouvrement.", M: "{crop}: {stage} from {start} to {end} falls right in the stress — {days} d overlap."},
    "reason.partial": {MS: "{crop} : {stage} du {start} au {end} tombe partiellement dans la tension — {days} j de recouvrement.", M: "{crop}: {stage} from {start} to {end} falls partly in the stress — {days} d overlap."},

    "cmp.same": {MS: "Choisissez deux cultures différentes pour comparer.", M: "Choose two different crops to compare."},
    "cmp.gain": {MS: "Remplacer {a} par {b} apporte +{diff} €/ha{water}.", M: "Replacing {a} with {b} brings +{diff} €/ha{water}."},
    "cmp.cost": {MS: "Remplacer {a} par {b} coûte {diff} €/ha de marge sur ce scénario.", M: "Replacing {a} with {b} costs {diff} €/ha of margin on this scenario."},
    "cmp.equal": {MS: "{a} et {b} ont une marge équivalente sur cette parcelle.", M: "{a} and {b} have an equivalent margin on this parcel."},
    "cmp.water_gain": {MS: " et réduit le besoin en eau", M: " and reduces the water need"},
    "cmp.label.water": {MS: "Eau", M: "Water"},
    "cmp.label.risk": {MS: "Risque", M: "Risk"},
    "cmp.label.margin": {MS: "Marge", M: "Margin"},
    "cmp.risk.none": {MS: "Aucun risque hydrique", M: "No water risk"},
    "cmp.risk.days": {MS: "{days} j sous tension", M: "{days} d under stress"},

    "no_risk.text": {MS: "Aucune culture ne nécessite d'ajustement : aucune ne croise la tension en eau prévue sur cette fenêtre.", M: "No crop needs adjustment: none crosses the water stress expected on this window."},

    # --- Étapes / sections ---------------------------------------------------------
    "step1.header": {MS: "1 · LE TUNNEL DE DÉCISION", M: "1 · THE DECISION TUNNEL"},
    "step1.title": {MS: "Du terrain au choix de culture", M: "From the field to the crop choice"},
    "step1.lead": {MS: "Deux écrans : votre parcelle, puis le résultat — classement, pourquoi, et le détail technique pour qui veut vérifier.", M: "Two screens: your parcel, then the result — ranking, why, and the technical detail for those who want to verify."},
    "step2.header": {MS: "2 · LE SCÉNARIO MÉTÉO", M: "2 · THE WEATHER SCENARIO"},
    "step2.title": {MS: "Du semis à la récolte, mois par mois", M: "From sowing to harvest, month by month"},
    "step2.lead": {MS: "Une frise par culture : la météo prévue mois par mois, avec le repère du moment où la culture est la plus exposée.", M: "One timeline per crop: the forecast weather month by month, with the marker of the moment the crop is most exposed."},
    "step3.header": {MS: "3 · L'AUDIT TECHNIQUE", M: "3 · THE TECHNICAL AUDIT"},
    "step3.title": {MS: "Ce qui a été collecté, rejeté et calculé", M: "What was collected, rejected and computed"},
    "step3.lead": {MS: "Le détail des chiffres, la confiance, les sources essayées et l'audit des données et des modèles — pour contrôler exactement ce que l'agent a fait.", M: "The detail of figures, confidence, sources tried and the data & model audit — to check exactly what the agent did."},
    "step.play": {MS: "▶ Lecture", M: "▶ Play"},
    "step2.calendar": {MS: "Voir le calendrier détaillé", M: "See the detailed calendar"},
    "step2.scroll.caption": {MS: "Besoins d'irrigation répartis sur le cycle de chaque culture, avec la fenêtre de tension hydrique (mêmes données que les frises ci-dessus).", M: "Irrigation needs spread over each crop's cycle, with the water stress window (same data as the timelines above)."},
    "step3.tab.numbers": {MS: "Chiffres & confiance", M: "Figures & confidence"},
    "step3.tab.provenance": {MS: "D'où viennent les données", M: "Where data comes from"},
    "step3.tab.expert": {MS: "Vue experte", M: "Expert view"},
    "step3.tab.security": {MS: "Test de sécurité", M: "Security test"},
    "step3.provenance.sub": {MS: "Sources de secours essayées", M: "Fallback sources tried"},
    "step3.table.col.culture": {MS: "Culture", M: "Crop"},
    "step3.table.col.days": {MS: "Jours à risque", M: "Risk days"},
    "step3.table.col.water": {MS: "Eau (mm)", M: "Water (mm)"},
    "step3.table.col.budget": {MS: "Budget irrigation (€/ha)", M: "Irrigation budget (€/ha)"},
    "step3.table.col.margin": {MS: "Résultat estimé (€/ha)", M: "Estimated result (€/ha)"},
    "step3.frontier.title": {MS: "TEST DE SÉCURITÉ", M: "SECURITY TEST"},
    "step3.frontier.h": {MS: "Que se passe-t-il si une station ne répond plus ?", M: "What happens if a station stops responding?"},
    "step3.frontier.p": {MS: "La Sentinelle suit les calculs dépendants et barre automatiquement les recommandations devenues fragiles.", M: "The Sentinelle tracks dependent computations and automatically strikes out recommendations that became fragile."},
    "step3.fail.btn": {MS: "Simuler une panne de station", M: "Simulate a station failure"},
    "step3.fail.msg": {MS: "{invalidated} recommandations invalidées. Rapport d'impact enregistré.", M: "{invalidated} recommendations invalidated. Impact report saved."},
    "step3.fail.incident": {MS: "Incident ouvert dans le graphe DataHub : {urn}", M: "Incident opened in the DataHub graph: {urn}"},
    "step3.fail.impact": {MS: "impact linéaire", M: "linear impact"},
    "step3.fail.entities": {MS: "entités invalidées", M: "entities invalidated"},
    "step3.fail.touched": {MS: "Éléments touchés", M: "Affected items"},
    "step3.fail.restore": {MS: "Rétablir la station et recalculer", M: "Restore the station and recompute"},
    "step3.final.title": {MS: "Avant de décider", M: "Before you decide"},
    "step3.final.text": {MS: "Confirmez l'analyse de sol, vos prix, vos charges, votre accès à l'eau et la place de la culture dans votre rotation avec votre conseiller.", M: "Confirm the soil analysis, your prices, your costs, your water access and the crop's place in your rotation with your advisor."},
    "step3.final.link": {MS: "Voir le projet, les sources et les limites", M: "See the project, sources and limits"},
    "nav.prev": {MS: "← Précédent", M: "← Back"},
    "nav.next": {MS: "Suivant →", M: "Next →"},
    "nav.tunnel_prev": {MS: "‹ Précédent", M: "‹ Back"},
    "nav.tunnel_result": {MS: "Suivant — Le résultat →", M: "Next — The result →"},
    "nav.tunnel_weather": {MS: "Voir le scénario météo →", M: "See the weather scenario →"},
    "nav.back_result": {MS: "← Retour au résultat", M: "← Back to the result"},
    "nav.to_details": {MS: "Voir les détails techniques →", M: "See the technical details →"},
    "nav.to_weather": {MS: "← Retour au scénario météo", M: "← Back to the weather scenario"},
    "steps.label1": {MS: "Parcelle & résultat", M: "Parcel & result"},
    "steps.label2": {MS: "Scénario météo", M: "Weather scenario"},
    "steps.label3": {MS: "Détails techniques", M: "Technical details"},

    # --- Vue données & IA -----------------------------------------------------------
    "datah.head.title": {MS: "Un graphe de contexte vif, sous contrôle", M: "A live context graph, under control"},
    "datah.head.lead": {MS: "Chaque chiffre de l'application est lu dans le graphe DataHub, contrôlé par la Sentinelle et tracé du capteur jusqu'à la recommandation.", M: "Every figure in the app is read in the DataHub graph, checked by the Sentinelle and traced from sensor to recommendation."},
    "datah.tab.kpis": {MS: "KPIs", M: "KPIs"},
    "datah.tab.supervision": {MS: "Supervision de l'agent", M: "Agent supervision"},
    "datah.tab.provenance": {MS: "Provenance", M: "Provenance"},
    "datah.tab.lineage": {MS: "Graphe de lineage", M: "Lineage graph"},
    "datah.banner.connect": {MS: "Graphe de contexte DataHub — connecté", M: "DataHub context graph — connected"},
    "datah.banner.freshness": {MS: "source(s) à jour · périmées · inconnues", M: "source(s) up to date · stale · unknown"},
    "datah.banner.local": {MS: "Graphe de contexte DataHub — mode démonstration locale", M: "DataHub context graph — local demo mode"},
    "datah.banner.local.text": {MS: "L'agent fonctionne sur {file} ({sources} sources, {edges} relations de lineage). Définissez {env} pour lire la fraîcheur dans DataHub et écrire runs et incidents dans le graphe.", M: "The agent runs on {file} ({sources} sources, {edges} lineage relations). Set {env} to read freshness in DataHub and write runs and incidents to the graph."},
    "datah.banner.unreachable": {MS: "Graphe DataHub injoignable", M: "DataHub graph unreachable"},
    "datah.banner.unreachable.text": {MS: "Repli local : les métadonnées de {file} sont utilisées. {url} ne répond pas.", M: "Local fallback: the metadata of {file} is used. {url} does not respond."},
    "datah.fresh.stale": {MS: "dépassé de {days} j (SLA {sla} j)", M: "stale by {days} d (SLA {sla} d)"},
    "datah.fresh.ok": {MS: "à jour", M: "up to date"},
    "datah.fresh.unknown": {MS: "inconnue", M: "unknown"},

    # --- Contact ---------------------------------------------------------------------
    "contact.title": {MS: "Discuter d'une parcelle, d'un territoire ou du projet", M: "Talk about a parcel, a territory or the project"},
    "contact.lead": {MS: "Le prototype fonctionne sur des données de démonstration. Pour une expérimentation sur votre exploitation ou votre territoire, écrivez-nous.", M: "The prototype runs on demo data. For an experiment on your farm or territory, write to us."},
    "contact.team": {MS: "ÉQUIPE", M: "TEAM"},
    "contact.code": {MS: "CODE & DONNÉES", M: "CODE & DATA"},
    "contact.live": {MS: "LIVE", M: "LIVE"},
    "contact.app": {MS: "Application complète : tunnel, scénario météo, audits", M: "Full application: tunnel, weather scenario, audits"},

    # --- Divers -----------------------------------------------------------------------
    "demo.auto": {MS: "▶ Démo auto (vidéo)", M: "▶ Auto demo (video)"},
    "demo.stop": {MS: "■ Arrêter", M: "■ Stop"},
    "cert.statement": "",  # placeholder non utilisé
}

_MONTHS = {
    "fr": {1: "Janv", 2: "Févr", 3: "Mars", 4: "Avr", 5: "Mai", 6: "Juin", 7: "Juil", 8: "Août", 9: "Sept", 10: "Oct", 11: "Nov", 12: "Déc"},
    "en": {1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"},
}


def default_lang() -> str:
    """Langue par défaut : fr."""
    return MS


def lang() -> str:
    """Langue courante de la session Streamlit (hors Streamlit : fr)."""
    try:
        from streamlit import session_state

        value = session_state.get("lang", MS)
        return value if value in {MS, M} else MS
    except Exception:
        return MS


def T(key: str, **fmt) -> str:
    """Libellé traduit pour la langue de la session (usage widget/app)."""
    return t(lang(), key, **fmt)


def t(lg: str, key: str, **fmt) -> str:
    """Libellé traduit pour une langue explicite (usage composants HTML)."""
    text = MSG[key][lg if lg in MSG[key] else MS]
    return text.format(**fmt) if fmt else text


def month_labels(lg: str) -> dict[int, str]:
    """Abréviations de mois selon la langue."""
    return _MONTHS[lg if lg in _MONTHS else MS]